server :
  port : 8080
  servlet :
    context-path : /

spring:
  datasource:
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/fourth


  jpa :
    hibernate :
      ddl-auto : create-drop